-- Create database for the project
CREATE DATABASE IF NOT EXISTS flightiq;

-- Use the database
USE flightiq;

-- Create external table over Parquet data stored in HDFS
CREATE EXTERNAL TABLE IF NOT EXISTS flights_clean (
    DAY_OF_MONTH INT,
    DAY_OF_WEEK INT,
    FL_DATE STRING,
    OP_UNIQUE_CARRIER STRING,
    OP_CARRIER_FL_NUM STRING,
    ORIGIN STRING,
    ORIGIN_CITY_NAME STRING,
    ORIGIN_STATE_ABR STRING,
    DEST STRING,
    DEST_CITY_NAME STRING,
    DEST_STATE_ABR STRING,
    CRS_DEP_TIME INT,
    DEP_TIME INT,
    DEP_DELAY DOUBLE,
    DEP_DELAY_NEW DOUBLE,
    DEP_DEL15 INT,
    CRS_ARR_TIME INT,
    ARR_TIME INT,
    ARR_DELAY DOUBLE,
    ARR_DELAY_NEW DOUBLE,
    ARR_DEL15 INT,
    CANCELLED INT,
    CANCELLATION_CODE STRING,
    DIVERTED INT,
    DISTANCE INT,
    CARRIER_DELAY DOUBLE,
    WEATHER_DELAY DOUBLE,
    NAS_DELAY DOUBLE,
    SECURITY_DELAY DOUBLE,
    LATE_AIRCRAFT_DELAY DOUBLE,
    IS_DELAYED INT
)
PARTITIONED BY (YEAR INT, MONTH INT)
STORED AS PARQUET
LOCATION 'hdfs://namenode:9000/cleaned/flights_clean';

-- Add existing partitions to the table
MSCK REPAIR TABLE flights_clean;

-- Show table structure for verification
DESCRIBE FORMATTED flights_clean;

-- Show available partitions
SHOW PARTITIONS flights_clean;